const APIPath = process.env.VUE_APP_WEB_API;
 const WEATHERICON = process.env.VUE_APP_ICON_WEATHER;
 const LOCAL_STORAGE_KEY = process.env.VUE_APP_LOCAL_STORAGE_KEY; 
export { APIPath ,WEATHERICON,LOCAL_STORAGE_KEY}

